server:
  port: ${IMAGE_PORT}

spring:
  kafka:
    consumer:
      bootstrap-servers: ${KAFKA_URL}
      group-id: image-consumer-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    listener:
      ack-mode: record


  datasource:
    url: ${IMAGE_DB_URL}
    username: ${IMAGE_DB_USERNAME}
    password: ${IMAGE_DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: create # 또는 create, create-drop, none, validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true

image:
  upload:
    dir: C:/Users/soh10/Desktop/dev/ProjectTeamBind/backend/service/image/uploads

    nginx:
      url: http:localhost:9002


logging:
  level:
    org.springframework.kafka: INFO
    bind.mail: DEBUG

