spring:
  datasource:
    url: ${OUTBOX_DB_URL}
    username: ${OUTBOX_DB_USERNAME}
    password: ${OUTBOX_DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true

outbox:
  kafka:
    topic: bind.events

logging:
  level:
    com.bind.outbox: DEBUG
