server:
  port: ${AUTH_PORT}



spring:
  datasource:
    url: ${AUTH_DB_URL}
    username: ${AUTH_DB_USERNAME}
    password: ${AUTH_DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
